services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-01-schema.sql:/docker-entrypoint-initdb.d/db-01-schema.sql
      - ./db-02-seed.sql:/docker-entrypoint-initdb.d/db-02-seed.sql
    networks:
      - fullcycle-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s

  nodejs:
    image: node:22
    container_name: nodejs
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - fullcycle-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 5s
    depends_on:
        mysql:
          condition: service_healthy  
    command: bash -c "npm install && node index.js"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fullcycle-network
    depends_on:
      nodejs:
        condition: service_healthy

networks:
  fullcycle-network:

